#!/bin/sh

run() {
	while [ true ]; do
		# Verify login server at 8080 is up and responding in a timely manner.
		ok=$(wget -O - --tries=1 --timeout=20 http://localhost:8080 2>/dev/null | grep -q IGLOOPORTAL && echo ok)
		if [ "$ok" != "ok" ]; then
			pids=$(ps waxf | grep apache2.*innproxy | grep -v grep | awk '{print $1}')
			echo "TIMEOUT pids=$pids" >/var/log/innproxy-8080.log
			[ "$pids" != "" ] && kill $pids
		fi	
		# If nothing is listening on :8080 (perhaps because of above shutdown), kill children and restart server.
		netstat -nlp | grep -q "^tcp.*:8080 " || {
			# Shutdown extra apache processes
			pids=$(ps waxf | grep apache2.*innproxy | grep -v grep | awk '{print $1}')
			[ "$pids" != "" ] && kill -9 $pids
			# Remove extra IPC semaphores
			numipcs=$(ipcs -s | grep www-data | wc -l)
			[ "$numipcs" -gt 10 ] && echo "IPCS Overkill" && ipcs -s | grep www-data | awk ' {print $2 } ' | xargs -n 1 ipcrm -s
			# Start Apache itself
			/usr/sbin/apache2 -f /var/lib/innproxy/apache2.conf -DNO_DETACH &
		}
		sleep 60
	done
}

start() {
	run &
        sleep 1
	status
}

stop() {
	pids=$(ps waxf | egrep "apache2.*innproxy|innproxy.*start" | grep -v grep | awk '{print $1}')
	echo "PIDS: $pids"
	[ "$pids" != "" ] && kill -9 $pids
}

status() {
        netstat -nlp | egrep ":80|:443|:447"
}

case $1 in
	start)
		echo "Starting innproxy..."
		start
	;;
	status)
		echo "Status of innproxy..."
		status
	;;
	stop)
		echo "Stopping innproxy..."
		stop
	;;
	restart)
		echo "Restarting innproxy..."
		stop
		start
	;;
	*)
		echo "Parameters: start, stop, restart, or status"
		exit 1
	;;
esac

