#!/bin/sh

ip=$1
[ "$1" = "" ] && echo "Missing IP address" 1>&2 && exit 1

# Extract MAC address from arp table
arpmac() {
	ip=$1
	arp -an | grep -v "<incomplete>" | grep ".*($ip)" | sed -e 's/.*(.*).*at.*\([0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]\) .*/\1/g'
}

mac=$(arpmac "$1")
if [ "$mac" = "" ]; then # If not found the first time may have timed out or never been accessed before
	ping -c 1 -f -w 0 -W 1 "$ip" >/dev/null 2>&1 # Bring into arp table
	#arping -w 0 -c 1 -I br0 "$ip" >/dev/null # Bring into arp table
	mac=$(arpmac "$1")
fi
echo "$mac"
