#!/usr/bin/perl

use strict;
use warnings;

use EBox;
use EBox::Users::User;

my $datestamp = POSIX::strftime("%s", localtime);

EBox::init();

my $parent = EBox::Users::User->defaultContainer();

open (my $USERS, 'users.csv');

while (my $line = <$USERS>) {
    chomp ($line);
    my ($username, $givenname, $surname, $password, $seconds) = split(',', $line);
	printf "ADD uid=$username,seconds=$seconds\n";
	eval {
		my $dn="uid=$username,ou=Users,dc=bristolinn,dc=com";
		my $user = new EBox::Users::User(dn => $dn);
		printf("DEL: %s\n",$user->description);
		$user->deleteObject();
	};
#	if ($@) { printf("DEL: %s",$@); }
	eval {
	    EBox::Users::User->create(
	    uid => $username,
		parent => $parent,
		givenname => $givenname,
		surname => $surname,
		description => "$password $datestamp $seconds",
		password => $password
	    );
	};
	if($@) {
		printf("ADD: %s",$@);
	}
}

close ($USERS);
printf("END\n");

1;
