#!/bin/bash

[ "$1" = "" ] && echo "Missing cookie value" 1>&2 && exit 1
cookie=$1

#grep "^192.168.2..* - [12][0-9][0-9].* .*EBox::CaptivePortal::Auth_EBox=$cookie\"" /var/log/zentyal-captiveportal/access.log | head -n 1 | awk '{print $3}'
cat /var/lib/zentyal-captiveportal/sessions/${cookie:0:32} | grep user: | cut -d "'" -f 2
