#!/usr/bin/awk -f

BEGIN {
	FS=",";
	print "<table>";
	print "  <tr><th colspan=\"3\">Available Access Codes</th></tr>";
	print "  <tr><th></th><th class=\"mid\"></th><th></th></tr>";
}
NR%3==1 &&  NR>1 { print "  </tr>"; }
NR%3==1 {
	print "  <tr>";
}

{
	print "    <td align=center><a href=\"activate.php?uid="$1"\">User: "$1"<br />Pass: "$2"</a></td>";
};

END { print "</tr>\n</table>"; }
