#!/bin/sh

[ "$1" = "" ] && echo "Missing user id" 1>&2 && exit 1

LOG="/var/log/zentyal-captiveportal/access.log"
TAG="EBox::CaptivePortal::Auth_EBox="
STAG='s/.*"EBox::CaptivePortal::Auth_EBox=/"EBox::CaptivePortal::Auth_EBox=/g'

listtags() {
	grep "^192.168.2..* - $1 " "$LOG" | grep "$TAG" | sed -e "$STAG" | sort | uniq
}

usage() {
	echo $(listtags "$1" | while read tag; do grep "$tag" "$LOG"; done | cut -d '"' -f 3 | awk '{print $2}' | grep -v "^-") | sed -e 's/ /+/g' | bc
}

listtags "$1"

