#!/bin/bash

[ "$1" = "" ] && echo "Missing user id" 1>&2 && exit 1
uid=$1

LOG="/var/log/zentyal-captiveportal/access.log"
SLOG="/var/log/squid3/access.log"

ipuser() {
	uid=$1
	grep "^192.168.2..* - $uid " "$LOG" | cut -d ']' -f 1
	date +"192.168.2.00 - $uid [%d/%b/%Y:%H:%M:%S %z"
}

listips() {
	uid=$1
	ipuser=""
	oip="192.168.2.00"
	ods="0000000000"
	ipuser "$uid" | while read line; do # For each access logged for this user
		ipuser=$(echo "$line" | cut -d '[' -f 1)
		# ipuser e.g. 192.168.2.64 - 105 [23/Oct/2013:09:53:13 -0800
		[ "$ipuser" != "$oipu" ] && echo "$line"
		oipu=$ipuser
	done | while read -r ip x uid ds tz; do # For each change in IP address
		ds=$(echo "$ds $tz" | sed -e 's@\[\([0-9]*\)/\(.*\)/\([0-9]*\):@\1 \2 \3 @g') # Make recognizable by date
		ds=$(date --date "$ds" +"%s")
		echo "$oip $uid $ods $ds"
		oip=$ip
		ods=$ds
	done
}

listuse() {
	uid=$1
	iphistory=$(listips "$uid" | tail -n +2) # IPs this user has had
	ips=$(echo "$iphistory" | cut -d ' ' -f 1 | sort | uniq)
	ips=$(echo $ips | sed -e 's/ / | /g')
	d=$(date +"%s-86400" | bc)
	dsipbytes=$(less $SLOG* | sort | awk "\$1 > $d {print \$1\" \"\$3\" \"\$5}" | grep -v "[A-Z][A-Z]*/[0-9][0-9]*" | sed -e 's/^"//g' | egrep " $ips ")
	if [ "$iphistory" != "" -a "$dsipbytes" != "" ]; then
		echo "$iphistory" | while read -r ip uid ods ds; do # For each IP address this user has had
			#echo "ods=$ods,ds=$ds,END"
			echo "$dsipbytes" | grep " $ip " | awk "\$1 >= $ods && \$1 <= $ds {print \$3}"
		done | awk '{s+=$1} END {print s/1024/1024}' # Sum of usage in megabytes
	else
		echo 0
	fi
}

printf "%7.2f\n" $(listuse "$uid")
#sleep 1 # Slow down so we don't overuse the CPU
