#!/usr/bin/perl

use strict;
use warnings;

use EBox;
use EBox::Users::User;
use Text::Password::Pronounceable;

# my $datestamp = POSIX::strftime("%s", localtime);

EBox::init();

my $parent = EBox::Users::User->defaultContainer();

    my $username = "" . $ARGV[0];
    my $password = uc(Text::Password::Pronounceable->generate(6,6));
	printf "ADD uid=$username\n";
	eval {
		my $dn="uid=$username,ou=Users,dc=bristolinn,dc=com";
		my $user = new EBox::Users::User(dn => $dn);
		printf("DEL: %s %s\n",$user->name,$user->description);
		$user->deleteObject();
	};
#	if ($@) { printf("DEL: %s",$@); }
	eval {
	    EBox::Users::User->create(
	    uid => $username,
		parent => $parent,
		givenname => substr($username,0,5) eq "diner"?"Diner":"Room",
		surname => $username,
		description => "$password 0 3600",
		password => $password
	    );
	};
	if($@) {
		printf("ADD: %s",$@);
	}

1;
