#!/bin/sh

# Block given uid from access, then delete it.

[ "$1" = "" ] && echo "Missing uid" 1>&2 && exit 1
uid=$1

sudo /home/administrator/scripts/logout "$uid"
sudo /home/administrator/scripts/deluid "$uid"
