#!/usr/bin/perl

use strict;
use warnings;

use EBox;
use EBox::Users::User;
use Text::Password::Pronounceable;

my $datestamp = POSIX::strftime("%s", localtime);

EBox::init();

my $parent = EBox::Users::User->defaultContainer();

my ($username) = ($ARGV[0]);
eval {
	my $dn="uid=$username,ou=Users,dc=bristolinn,dc=com";
	my $user = new EBox::Users::User(dn => $dn);
	my ($password, $timestamp, $seconds) = split(' ', $user->description);
	$password =~ s/_/ /g;
	printf("%s<br />%s\n",$user->name,$password);
};
if ($@) { printf("LIST: %s",$@); }

1;
