#!/usr/bin/perl

use strict;
use warnings;

use EBox;
use EBox::Users::User;

EBox::init();

my $usersMod = EBox::Global->modInstance('users');
my $users = $usersMod->users();
my $h1 = "";
my $h2 = "";
my $h3 = "";

foreach my $user (@$users) {
	printf("%s %s\n",$user->name,$user->description);
}

1;
