#!/usr/bin/perl

use strict;
use warnings;

use EBox;
use EBox::Users::User;
use Text::Password::Pronounceable;

EBox::init();

my $parent = EBox::Users::User->defaultContainer();

my ($username, $description) = ($ARGV[0],$ARGV[1]);
$username = "diner" . $username;
printf "MOD uid=$username,description=$description\n";
eval {
	my $dn="uid=$username,ou=Users,dc=bristolinn,dc=com";
	my $user = new EBox::Users::User(dn => $dn);
	$user->set('description',$description);
	$user->save();
	printf "MOD uid=$username,description=" . $user->description . "\n";
};
if ($@) { printf("MOD: %s",$@); }

1;
